"""순환참조 에러 업데이트

Revision ID: 01fc0e83bc7a
Revises: 1ecee6ac3025
Create Date: 2025-08-12 17:35:45.407208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# pgvector 관련 import (필요시)
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '01fc0e83bc7a'
down_revision: Union[str, Sequence[str], None] = '1ecee6ac3025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=True)
    # ### end Alembic commands ###
