"""item id 외부 동기화

Revision ID: 0b23f081d071
Revises: 2e086fd12079
Create Date: 2025-08-07 22:31:42.108471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# pgvector 관련 import (필요시)
# import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0b23f081d071'
down_revision: Union[str, Sequence[str], None] = '2e086fd12079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=True)
    # ### end Alembic commands ###
