"""Remove processing_status column

Revision ID: 684968767c83
Revises: 2d71f550d991
Create Date: 2025-12-04 14:55:09.425856

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "684968767c83"
down_revision: Union[str, None] = "2d71f550d991"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """업그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """다운그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
