"""Add summary_status and embedding_status to contents

Revision ID: 2d71f550d991
Revises: 035bdc961929
Create Date: 2025-12-04 14:44:50.560113

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2d71f550d991"
down_revision: Union[str, None] = "035bdc961929"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """업그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_users_active"),
        table_name="users",
        postgresql_where="(deleted_at IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """다운그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_users_active"),
        "users",
        ["id"],
        unique=False,
        postgresql_where="(deleted_at IS NULL)",
    )
    # ### end Alembic commands ###
