"""create_ai_domain_tables

Revision ID: 054266193b8b
Revises: cd73cace0511
Create Date: 2025-12-05 00:37:09.768488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "054266193b8b"
down_revision: Union[str, None] = "cd73cace0511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """업그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "category_name",
            sa.String(length=100),
            nullable=False,
            comment="카테고리 이름",
        ),
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
            comment="카테고리 임베딩 벡터 (1536 차원)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("category_name"),
    )
    op.create_table(
        "chunk_strategies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="전략 이름 (예: default, pdf-academic, webpage-news)",
        ),
        sa.Column(
            "content_type",
            sa.String(length=50),
            nullable=True,
            comment="적용할 콘텐츠 타입 (webpage, youtube, pdf)",
        ),
        sa.Column(
            "domain",
            sa.String(length=100),
            nullable=True,
            comment="적용할 도메인 (예: tech, news, academic)",
        ),
        sa.Column(
            "chunk_size", sa.Integer(), nullable=False, comment="청크 크기 (토큰 수)"
        ),
        sa.Column(
            "chunk_overlap",
            sa.Integer(),
            nullable=False,
            comment="청크 간 겹침 (토큰 수)",
        ),
        sa.Column(
            "split_method",
            sa.String(length=50),
            nullable=False,
            comment="분할 방법 (token, sentence, paragraph)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="활성화 여부"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="수정일시",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "contents",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="콘텐츠 ID",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="사용자 ID (Spring Boot 동기화)",
        ),
        sa.Column(
            "content_type",
            sa.String(length=20),
            nullable=False,
            comment="콘텐츠 타입 (webpage/youtube/pdf)",
        ),
        sa.Column(
            "summary_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="요약 생성 상태 (AI 도메인 독립 프로세스)",
        ),
        sa.Column(
            "embedding_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
            comment="임베딩 생성 상태 (AI 도메인 독립 프로세스)",
        ),
        sa.Column(
            "source_url",
            sa.Text(),
            nullable=True,
            comment="원본 URL (웹페이지/YouTube만)",
        ),
        sa.Column(
            "file_hash",
            sa.String(length=64),
            nullable=True,
            comment="파일 해시 SHA-256 (PDF만)",
        ),
        sa.Column(
            "title", sa.String(length=500), nullable=False, comment="콘텐츠 제목"
        ),
        sa.Column(
            "summary", sa.Text(), nullable=True, comment="AI 생성 또는 사용자 확정 요약"
        ),
        sa.Column("thumbnail", sa.Text(), nullable=True, comment="썸네일 URL"),
        sa.Column("memo", sa.Text(), nullable=True, comment="사용자 메모"),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            nullable=True,
            comment="태그 목록 (PostgreSQL ARRAY)",
        ),
        sa.Column(
            "category", sa.String(length=100), nullable=True, comment="카테고리"
        ),
        sa.Column(
            "raw_source",
            sa.Text(),
            nullable=True,
            comment="원본 HTML/자막 (웹페이지/YouTube만)",
        ),
        sa.Column(
            "raw_content", sa.Text(), nullable=True, comment="AI 추출 텍스트"
        ),
        sa.Column(
            "extraction_method",
            sa.String(length=50),
            nullable=True,
            comment="추출 방법 (AI 모델명 등)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성 일시",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="수정 일시",
        ),
        sa.Column(
            "deleted_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="삭제 일시 (Soft Delete)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_contents_content_type",
        "contents",
        ["content_type", "user_id"],
        unique=False,
    )
    op.create_index(
        "ix_contents_created_at", "contents", ["created_at"], unique=False
    )
    op.create_index(
        "ix_contents_embedding_status",
        "contents",
        ["embedding_status"],
        unique=False,
    )
    op.create_index(
        "ix_contents_source_url", "contents", ["source_url"], unique=False
    )
    op.create_index(
        "ix_contents_summary_status",
        "contents",
        ["summary_status"],
        unique=False,
    )
    op.create_index(
        "ix_contents_user_id_not_deleted",
        "contents",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "summary_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "cache_key",
            sa.String(length=64),
            nullable=False,
            comment="캐시 키 (URL 또는 파일 해시의 SHA-256)",
        ),
        sa.Column(
            "cache_type",
            sa.String(length=20),
            nullable=False,
            comment="캐시 타입 (webpage, youtube, pdf)",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="콘텐츠 해시 (변경 감지용)",
        ),
        sa.Column(
            "extracted_text", sa.Text(), nullable=True, comment="추출된 텍스트"
        ),
        sa.Column("summary", sa.Text(), nullable=True, comment="생성된 요약"),
        sa.Column(
            "candidate_tags",
            sa.ARRAY(sa.String()),
            nullable=True,
            comment="추천 태그 후보 (PostgreSQL ARRAY)",
        ),
        sa.Column(
            "candidate_categories",
            sa.ARRAY(sa.String()),
            nullable=True,
            comment="추천 카테고리 후보 (PostgreSQL ARRAY)",
        ),
        sa.Column(
            "chunk_embeddings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="청크별 임베딩 정보 (JSONB)",
        ),
        sa.Column(
            "wtu_cost",
            sa.Integer(),
            nullable=True,
            comment="원본 생성 시 사용된 WTU (캐시 히트 시 동일 부과)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="수정일시",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="만료일시 (TTL 30일)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_summary_cache_cache_key"),
        "summary_cache",
        ["cache_key"],
        unique=True,
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "tag_name", sa.String(length=100), nullable=False, comment="태그 이름"
        ),
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
            comment="태그 임베딩 벡터 (1536 차원)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag_name"),
    )
    op.create_table(
        "content_embedding_metadatas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "content_id", sa.Integer(), nullable=False, comment="연결된 콘텐츠 ID"
        ),
        sa.Column(
            "strategy_id", sa.Integer(), nullable=True, comment="사용된 청크 전략 ID"
        ),
        sa.Column(
            "chunk_index", sa.Integer(), nullable=False, comment="청크 순서"
        ),
        sa.Column(
            "chunk_content", sa.Text(), nullable=False, comment="청크 텍스트 내용"
        ),
        sa.Column(
            "start_position",
            sa.Integer(),
            nullable=True,
            comment="원본 텍스트에서의 시작 위치",
        ),
        sa.Column(
            "end_position",
            sa.Integer(),
            nullable=True,
            comment="원본 텍스트에서의 종료 위치",
        ),
        sa.Column(
            "embedding_vector",
            pgvector.sqlalchemy.Vector(dim=3072),
            nullable=True,
            comment="임베딩 벡터 (3072 차원)",
        ),
        sa.Column(
            "embedding_model",
            sa.String(length=100),
            nullable=False,
            comment="임베딩 모델명",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="생성일시",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["chunk_strategies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_embedding_metadatas_content_id"),
        "content_embedding_metadatas",
        ["content_id"],
        unique=False,
    )
    op.create_table(
        "user_category_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="사용자 ID"),
        sa.Column(
            "category_id", sa.Integer(), nullable=False, comment="카테고리 ID"
        ),
        sa.Column("use_count", sa.Integer(), nullable=False, comment="사용 횟수"),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="마지막 사용일시",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_id", name="uq_user_category"),
    )
    op.create_index(
        op.f("ix_user_category_usage_user_id"),
        "user_category_usage",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_tag_usage",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="사용자 ID"),
        sa.Column("tag_id", sa.Integer(), nullable=False, comment="태그 ID"),
        sa.Column("use_count", sa.Integer(), nullable=False, comment="사용 횟수"),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="마지막 사용일시",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tag_id", name="uq_user_tag"),
    )
    op.create_index(
        op.f("ix_user_tag_usage_user_id"),
        "user_tag_usage",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """다운그레이드 마이그레이션"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_tag_usage_user_id"), table_name="user_tag_usage"
    )
    op.drop_table("user_tag_usage")
    op.drop_index(
        op.f("ix_user_category_usage_user_id"),
        table_name="user_category_usage",
    )
    op.drop_table("user_category_usage")
    op.drop_index(
        op.f("ix_content_embedding_metadatas_content_id"),
        table_name="content_embedding_metadatas",
    )
    op.drop_table("content_embedding_metadatas")
    op.drop_table("tags")
    op.drop_index(
        op.f("ix_summary_cache_cache_key"), table_name="summary_cache"
    )
    op.drop_table("summary_cache")
    op.drop_index(
        "ix_contents_user_id_not_deleted",
        table_name="contents",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_contents_summary_status", table_name="contents")
    op.drop_index("ix_contents_source_url", table_name="contents")
    op.drop_index("ix_contents_embedding_status", table_name="contents")
    op.drop_index("ix_contents_created_at", table_name="contents")
    op.drop_index("ix_contents_content_type", table_name="contents")
    op.drop_table("contents")
    op.drop_table("chunk_strategies")
    op.drop_table("categories")
    # ### end Alembic commands ###
