"""item id 외부 동기화

Revision ID: 2e086fd12079
Revises: 6085999edaae
Create Date: 2025-08-07 22:28:51.472957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# pgvector 관련 import (필요시)
# import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '2e086fd12079'
down_revision: Union[str, Sequence[str], None] = '6085999edaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment='Spring Boot Item ID (동기화)',
               existing_comment='아이템 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index('ix_items_source_url', 'items', ['source_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_source_url', table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=False)
    op.alter_column('items', 'id',
               existing_type=sa.INTEGER(),
               comment='아이템 ID',
               existing_comment='Spring Boot Item ID (동기화)',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
