"""Add WTU metering and dedup suggestion tables

Revision ID: e2e28c83f915
Revises: 01fc0e83bc7a
Create Date: 2025-08-17 17:13:51.489336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# pgvector 관련 import (필요시)
# import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e2e28c83f915'
down_revision: Union[str, Sequence[str], None] = '01fc0e83bc7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedup_suggestion',
    sa.Column('id', sa.UUID(), nullable=False, comment='중복 제안 ID'),
    sa.Column('board_id', sa.UUID(), nullable=False, comment='보드 ID'),
    sa.Column('doc_ids', sa.ARRAY(sa.UUID()), nullable=False, comment='중복 후보 문서 ID 배열 (최소 2개)'),
    sa.Column('score', sa.Float(), nullable=False, comment='유사도 점수 (0.0-1.0)'),
    sa.Column('accepted', sa.Boolean(), nullable=False, comment='사용자 수락 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dedup_suggestion_accepted', 'dedup_suggestion', ['accepted'], unique=False)
    op.create_index('ix_dedup_suggestion_board_created', 'dedup_suggestion', ['board_id', 'created_at'], unique=False)
    op.create_index('ix_dedup_suggestion_score', 'dedup_suggestion', ['score'], unique=False)
    op.create_table('usage_meter',
    sa.Column('id', sa.UUID(), nullable=False, comment='사용량 기록 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('run_id', sa.UUID(), nullable=True, comment='실행 ID (배치 작업 시)'),
    sa.Column('in_tokens', sa.Integer(), nullable=False, comment='입력 토큰 수'),
    sa.Column('cached_in_tokens', sa.Integer(), nullable=False, comment='캐시된 입력 토큰 수'),
    sa.Column('out_tokens', sa.Integer(), nullable=False, comment='출력 토큰 수'),
    sa.Column('embed_tokens', sa.Integer(), nullable=False, comment='임베딩 토큰 수'),
    sa.Column('wtu', sa.Integer(), nullable=False, comment='계산된 WTU 값'),
    sa.Column('plan_month', sa.Date(), nullable=False, comment='계획 월 (YYYY-MM-01)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_meter_created_at', 'usage_meter', ['created_at'], unique=False)
    op.create_index('ix_usage_meter_plan_month', 'usage_meter', ['plan_month'], unique=False)
    op.create_index('ix_usage_meter_user_plan_month', 'usage_meter', ['user_id', 'plan_month'], unique=False)
    op.alter_column('item_tags', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='출처: ai, user',
               existing_comment='출처: ai, user, system',
               existing_nullable=True)
    op.drop_index(op.f('ix_items_source_url'), table_name='items')
    op.create_index('ix_items_source_url', 'items', ['source_url'], unique=True)
    
    # Add FTS column to items table for deduplication
    op.execute("""
        ALTER TABLE items 
        ADD COLUMN fts tsvector 
        GENERATED ALWAYS AS (
            to_tsvector('simple', 
                coalesce(title, '') || ' ' || 
                coalesce(description, '') || ' ' || 
                coalesce(summary, '')
            )
        ) STORED;
    """)
    
    # Create GIN index for FTS
    op.execute("CREATE INDEX ix_items_fts ON items USING GIN(fts);")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop FTS index and column
    op.execute("DROP INDEX IF EXISTS ix_items_fts;")
    op.execute("ALTER TABLE items DROP COLUMN IF EXISTS fts;")
    
    op.drop_index('ix_items_source_url', table_name='items')
    op.create_index(op.f('ix_items_source_url'), 'items', ['source_url'], unique=False)
    op.alter_column('item_tags', 'source',
               existing_type=sa.VARCHAR(length=20),
               comment='출처: ai, user, system',
               existing_comment='출처: ai, user',
               existing_nullable=True)
    op.drop_index('ix_usage_meter_user_plan_month', table_name='usage_meter')
    op.drop_index('ix_usage_meter_plan_month', table_name='usage_meter')
    op.drop_index('ix_usage_meter_created_at', table_name='usage_meter')
    op.drop_table('usage_meter')
    op.drop_index('ix_dedup_suggestion_score', table_name='dedup_suggestion')
    op.drop_index('ix_dedup_suggestion_board_created', table_name='dedup_suggestion')
    op.drop_index('ix_dedup_suggestion_accepted', table_name='dedup_suggestion')
    op.drop_table('dedup_suggestion')
    # ### end Alembic commands ###
